# Generated by Django 6.0.5 on 2026-05-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('doc', 'Doctor'), ('pat', 'Patient')], max_length=3),
        ),
    ]
