# Generated by Django 6.0.5 on 2026-05-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('doc', 'Doctor'), ('pat', 'Patient')], max_length=3),
        ),
    ]
