# Generated by Django 6.0.5 on 2026-06-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_notification_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('mal', 'Male'), ('fem', 'Female'), ('rat', 'Rather not say')], max_length=3),
        ),
    ]
