# Generated by Django 6.0.5 on 2026-06-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_bio_alter_doctor_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='next_available_appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
